name: avi_animator
description: A visual storyboard generator by Avi
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  image: ^4.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
